### ISSUE TITLE
Client fails when haste application is running on a non-default path on the server

### ISSUE THREAD

**Issue by vaibhav92** [seejohnrun/haste-client#26]
Haste client fails with an error when the hast application is running as non default application on the web-server. For example below command fails:

> [me@localhost haste]$ echo "hello" | HASTE_SERVER='**http://my.webserver.com/paste**' haste 
> _failure uploading: &lt;!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"&gt;
> &lt;html&gt;&lt;head&gt;
> &lt;title&gt;404 Not Found&lt;/title&gt;
> &lt;/head&gt;&lt;body&gt;
> &lt;h1&gt;Not Found&lt;/h1&gt;
> &lt;p&gt;The requested URL /documents was not found on this server.&lt;/p&gt;
> &lt;hr&gt;
> &lt;address&gt;Apache/2.2.15 (Fedora) Server at my.webserver.com Port 80&lt;/address&gt;
> &lt;/body&gt;&lt;/html&gt;_
> [me@localhost haste]$

**Comment by seejohnrun** [comment]
Closed via #27
