### ISSUE TITLE
haste-client lite improvement 

### ISSUE THREAD

**Issue by xenithorb** [seejohnrun/haste-client#30]
``` bash
haste () 
{
    local S="http" H="hastebin.com" P=""
    local SHP="${S}://${H}${P}/"
    curl -X POST -s --data-binary @- "${SHP}documents" \
        | awk -F '"' '{print a$4}' a="${SHP}"
}
```

This was what I ended up using internally. Yes, it's a little more complicated than the example, but the added functionality of `--data-binary @-` replacing `-d` is what allows me to send any size text file

I usually put this in /etc/profile.d as its own script so that it's loaded into the shell upon login. Could have gone the separate script in /usr/local/bin route, but this seemed simpler.

**Comment by seejohnrun** [comment]
Thanks! I know it's been a while but if you're still interested in this change maybe a PR against the README?
