### ISSUE TITLE
Language detection not 100% correct

### ISSUE THREAD

**Issue by DusterTheFirst** [seejohnrun/haste-client#37]
When saving JS code, it gets put down as PHP, Pearl and other languges.
This, most of the time, screws with syntax highlighing
I would love to see some sort of way to select the language manually.

I would create a fork and pull request but, alas, I do not know ruby

**Comment by DusterTheFirst** [comment]
Also, if this should be on the server repo, sorry in advance

**Comment by seejohnrun** [comment]
This is more connected to the `haste-server` repo, but really even there I won't be able to do much.  We depend on a library called [highlight.js](https://highlightjs.org/) for highlighting and take their results to feedback in `haste-server`.

I'd open an issue over there after checking to make sure the most recent version of highlight.js (which we are not on) doesn't fix the issue.

Thanks!
