### ISSUE TITLE
Document exceeds maximum length.

### ISSUE THREAD

**Issue by theraw** [seejohnrun/haste-client#43]
```bash
# cat error.log | haste
failure uploading: {"message":"Document exceeds maximum length."}
```
any solution or run my own server only?

**Comment by youngchief-btw** [comment]
It has to do with a configuration option on the Haste server.
If you have your own server you can change this behavior in `config.js`
As for a workaround, you could split the file into multiple parts then upload each one of them individually (manually or automated) and then collect the URLs given back to you.
